my_contact_data/urls.py
from django.urls import include, path
from my_contact_data import views
 
app_name='my_contact_data'
 
urlpatterns = [
    path('',views.home,name='home'),
    path('books',views.books,name='aboutus'),
    path('ContactUs',views.ContactUs,name='contactdata'),
    path('Contact_form_submit',views.Contact_form_submit,name='Contact_form_submit')
]

my_project/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import path,include
urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('my_contact_data.urls')),



]

my_contact_data/models.py
from django.db import models

# Create your models here.
class ContactForm(models.Model):
    #Total Fields : 5
    #------Contact form Table Fields------

    #This field store Full Name 
    full_name = models.CharField(max_length=300,blank=True)
    #This field store Email ID
    email_id = models.CharField(max_length=300,blank=True)
    #This field store Contact Number 
    contact_number = models.CharField(max_length=300,blank=True)
    #This field store Message 
    message = models.TextField(max_length=3000,blank=True)
    #This field store Date & Time at which form is submitted
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.pk) #Return Primary Key

    class Meta:
        verbose_name_plural = "Contact Form Data"
        verbose_name = "Contact Form"


my_contact_data/views.py
from django.shortcuts import render
from my_contact_data.models import ContactForm
from django.shortcuts import render,HttpResponseRedirect,HttpResponse
from django.urls import reverse
# Create your views here.
def home(request):
    return render(request,'my_contact_data/home.html')
def books(request):
    return render(request,'my_contact_data/aboutus.html')

def ContactUs(request):
    my_contact_form_data = ContactForm.objects.all()
    data = {'my_contact_form_data' : my_contact_form_data }
    return render(request,'my_contact_data/contactdata.html')

def Contact_form_submit(request):
    if request.method == "POST":
        full_name = request.POST['full_name']
        email_id = request.POST['email_id']
        contact_number = request.POST['contact_number']
        message = request.POST['message']
        ContactForm.objects.create(full_name=full_name,
                                   email_id=email_id,
                                   contact_number=contact_number,
                                   message=message
                                   )
    return HttpResponseRedirect(reverse('my_contact_data:contactdata'))


my_contact_data/templates/my_contact_data/aboutus.html
{% extends 'my_contact_data/base.html' %}
{% load static %}

{% block stylesheets %}
<style>
    body {
        background-color: #E8E8E8;
    }

    .box {
        margin-top: 6rem;

    }

    ul {
        position: relative;
        right: 0;
    }

    .row input {
        margin-bottom: 2rem;
        border: 0;
        box-shadow: 0;
         !importatnt
    }

    .row textarea {
        margin-bottom: 2rem;
        border: 0;
    }

    .box h1 {
        margin-bottom: 2rem;
    }

    .icons {
        margin-top: 3rem;
    }

    .copy {
        margin-top: 1rem;
    }

    .icons a {
        color: #ccc;
        margin: 1rem;
    }

    .icons a:hover {
        color: #000;
    }





    * {
        box-sizing: border-box;
    }

    body {
        background-color: #f1f1f1;
        padding: 20px;
        font-family: Arial;
    }

    /* Center website */
    .main {
        max-width: 1000px;
        margin: auto;
    }

    h1 {
        font-size: 50px;
        word-break: break-all;
    }

    .row {
        margin: 8px -16px;
    }

    /* Add padding BETWEEN each column (if you want) */
    .row,
    .row>.column {
        padding: 8px;
    }

    /* Create three equal columns that floats next to each other */
    .column {
        float: left;
        width: 33.33%;
        display: none;
        /* Hide columns by default */
    }

    /* Clear floats after rows */
    .row:after {
        content: "";
        display: table;
        clear: both;
    }

    /* Content */
    .content {
        background-color: white;
        padding: 10px;
    }

    /* The "show" class is added to the filtered elements */
    .show {
        display: block;
    }

    /* Style the buttons */
    .btn {
        border: none;
        outline: none;
        padding: 12px 16px;
        background-color: white;
        cursor: pointer;

    }

    /* Add a grey background color on mouse-over */
    .btn:hover {
        background-color: #ddd;
    }

    /* Add a dark background color to the active button */
    .btn.active {
        background-color: #666;
        color: white;
    }
</style>
{% endblock stylesheets %}


{% block headscript %}
{% endblock headscript %}


{% block content %}


<div class="container">

    <div class="box shadow-lg p-3 mb-5 bg-white rounded">
        <div class="">
            <center>
                <h1 style="color: #15aabf">BOOKS WE RECOMMEND</h1>
            </center>
        </div>



        <div class="container">
            <div class="row">

                <div id="myBtnContainer">

                    <button class="btn active" onclick="filterSelection('all')"> Show all</button>
                    <button class="btn" onclick="filterSelection('historicalfic')"> Historical Fiction</button>
                    <button class="btn" onclick="filterSelection('literaryfic')"> Literary Fiction</button>
                    <button class="btn" onclick="filterSelection('memoirs')"> Memoirs</button>

                </div>


                <!-- Portfolio Gallery Grid -->
                <div class="row">
                    <div class="column historicalfic col-md-4">
                        <div class="content">
                            <img src="{% static 'my_contact_data/p.jpg' %}" alt="A Thousand Splendid Suns" style="width:100%;height: 300px">

                        </div>
                    </div>
                    <div class="column historicalfic col-md-4">
                        <div class="content">
                            <img src="{% static 'my_contact_data/kite.jpg' %}" alt="The Kite Runner" style="width:100%;height: 300px">

                        </div>
                    </div>
                    <div class="column historicalfic col-md-4">
                        <div class="content">
                            <img src="{% static 'my_contact_data/sil.jpg' %}" alt="The Fountains Of Silence" style="width:100%;height: 300px">

                        </div>
                    </div>

                    <div class="column literaryfic col-md-4">
                        <div class="content">
                            <img src="{% static 'my_contact_data/every.jpg' %}" alt="literaryfic" style="width:100%;height: 300px">

                        </div>
                    </div>
                    <div class="column literaryfic col-md-4">
                        <div class="content">
                            <img src="{% static 'my_contact_data/burn.jpg' %}" alt="literaryfic" style="width:100%;height: 300px">

                        </div>
                    </div>
                    <div class="column literaryfic col-md-4">
                        <div class="content">
                            <img src="{% static 'my_contact_data/wh.jpg' %}" alt="literaryfic" style="width:100%;height: 300px">

                        </div>
                    </div>

                    <div class="column memoirs col-md-4">
                        <div class="content">
                            <img src="{% static 'my_contact_data/anne.jpg' %}" alt="memoirs" style="width:100%;height: 300px">

                        </div>
                    </div>
                    <div class="column memoirs col-md-4">
                        <div class="content">
                            <img src="{% static 'my_contact_data/bec.jpg' %}" alt="memoirs" style="width:100%;height: 300px">

                        </div>
                    </div>
                    <div class="column memoirs col-md-4">
                        <div class="content">
                            <img src="{% static 'my_contact_data/edu.jpg' %}" alt="memoirs" style="width:100%;height: 300px">

                        </div>
                    </div>
                    <!-- END GRID -->
                </div>


            </div>
        </div>

    </div>
</div>
{% endblock %}

{% block script %}
<script>
    filterSelection("all") // Execute the function and show all columns
    function filterSelection(c) {
        var x, i;
        x = document.getElementsByClassName("column");
        if (c == "all") c = "";
        // Add the "show" class (display:block) to the filtered elements, and remove the "show" class from the elements that are not selected
        for (i = 0; i < x.length; i++) {
            w3RemoveClass(x[i], "show");
            if (x[i].className.indexOf(c) > -1) w3AddClass(x[i], "show");
        }
    }

    // Show filtered elements
    function w3AddClass(element, name) {
        var i, arr1, arr2;
        arr1 = element.className.split(" ");
        arr2 = name.split(" ");
        for (i = 0; i < arr2.length; i++) {
            if (arr1.indexOf(arr2[i]) == -1) {
                element.className += " " + arr2[i];
            }
        }
    }

    // Hide elements that are not selected
    function w3RemoveClass(element, name) {
        var i, arr1, arr2;
        arr1 = element.className.split(" ");
        arr2 = name.split(" ");
        for (i = 0; i < arr2.length; i++) {
            while (arr1.indexOf(arr2[i]) > -1) {
                arr1.splice(arr1.indexOf(arr2[i]), 1);
            }
        }
        element.className = arr1.join(" ");
    }

    // Add active class to the current button (highlight it)
    var btnContainer = document.getElementById("myBtnContainer");
    var btns = btnContainer.getElementsByClassName("btn");
    for (var i = 0; i < btns.length; i++) {
        btns[i].addEventListener("click", function() {
            var current = document.getElementsByClassName("active");
            current[0].className = current[0].className.replace(" active", "");
            this.className += " active";
        });
    }
</script>
{% endblock %}

my_contact_data/templates/my_contact_data/base.html
<!DOCTYPE html>
<html>
{% load static %}
<head>
    <title>BooksforLife</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
    <link rel='stylesheet' href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.1.0-4/css/all.css">
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    {% block stylesheets %}
    {% endblock stylesheets %}  
    
    {% block headscript %}
    {% endblock headscript %}
    <style>
        body {
            background-color: #E8E8E8;
        }
    </style>
</head>
<body>
    <div>
        <nav class="navbar navbar-expand-lg navbar-dark bg-info fixed-top">
            <a class="navbar-brand"><b>BooksforLife</b></a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
                <ul class="navbar-nav ml-auto ">
                    <li class="nav-item ">
                        <a class="nav-link" style="color: #fff" href="{% url 'my_contact_data:home' %}">About</a>
                    </li> 
                    <li class="nav-item ">
                        <a class="nav-link" style="color: #fff" href="{% url 'my_contact_data:aboutus' %}">Books We Love </a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" style="color: #fff" href="{% url 'my_contact_data:contactdata' %}">SignUp For More Discussions</a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
    {% block content %}
    {% endblock %}
    
    {% block script %}
    {% endblock %}
</body>
</html>




my_contact_data/templates/my_contact_data/contactdata.html
{% extends 'my_contact_data/base.html' %}
{% load static %}

{% block stylesheets %}
<style>
    .box {
        margin-top: 6rem;

    }

    ul {
        position: relative;
        right: 0;
    }

    .row input {
        margin-bottom: 2rem;
        border: 0;
        box-shadow: 0;
         !importatnt
    }

    .row textarea {
        margin-bottom: 2rem;
        border: 0;
    }

    .box h1 {
        margin-bottom: 5rem;
    }

    .icons {
        margin-top: 3rem;
    }

    .copy {
        margin-top: 1rem;
    }

    .icons a {
        color: #ccc;
        margin: 1rem;
    }

    .icons a:hover {
        color: #000;
    }
</style>

{% endblock stylesheets %}


{% block headscript %}
{% endblock headscript %}


{% block content %}
<div class="container">

    <div class="box shadow-lg p-3 mb-5 bg-white rounded">
        <div class="">
            <center>
                <h1 style="color: #15aabf">SIGN UP FOR OUR FREE NEWSLETTERS!!</h1>
            </center>
        </div>
        <div class=" container">
            <form method="POST" action="{%  url 'my_contact_data:Contact_form_submit' %}">
                {% csrf_token %}
                <div class="row">
                    <div class="form-group col-sm-4">
                        <input type="text" id="full_name" name="full_name" class="form-control form-control-lg border-bottom border-dark shadow-none" placeholder="Name">
                    </div>
                    <div class="form-group  col-sm-4">
                        <input type="text" id="email_id" name="email_id" class="form-control form-control-lg border-bottom border-dark shadow-none" placeholder="Email">
                    </div>
                    <div class="form-group col-sm-4">
                        <input type="text" id="contact_number" name="contact_number" class="form-control form-control-lg border-bottom border-dark shadow-none" placeholder="Contact">
                    </div>

                </div>
                <div class="row">
                    <div class="col-md-12">
                        <textarea id="message" name="message" class="form-control form-control-lg border-bottom border-dark shadow-none" rows="5" placeholder="Special Topics You Want To Discuss"></textarea>
                    </div>
                    <div class="col-md-12">
                        <center> <button type="submit" class="btn-info btn btn-lg">Submit</button></center>
                    </div>

                </div>
            </form>

        </div>
        <div class="container">
            <div class="icons">
                <center>
                    <a href="#"><span class="fab fa-twitter fa-2x"></span></a>
                    <a href="#"><i class="fab fa-instagram fa-2x"></i></a>
                </center>

            </div>
        </div>
        <div class="container">
            <div class="copy">
                <center>
                    <h6>&copy;2020 BooksforLife</h6>
                </center>

            </div>
        </div>
    </div>
</div>

{% endblock %}

{% block script %}
{% endblock %}


my_contact_data/templates/my_contact_data/home.html
{% extends 'my_contact_data/base.html' %}
{% load static %}
{% block stylesheets %}
<head>
	<meta charset="utf-8">
	<meta name="viewport" content="device-width,initial-scale=1">
	<title>First Bootstrap Project</title>
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css">
	<link rel="stylesheet"  href="https://use.fontawesome.com/releases/v5.7.0/css/all.css">
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
  	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.16.0/umd/popper.min.js"></script>
  	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"></script>
</head>
<body style="padding-top: 70px; font-family: Arial;">
	
		
	<div class="container">
		<div class="jumbotron bg-info ">
			<h2 class="text-body"><img src="http://pngimg.com/uploads/book/book_PNG2105.png" alt="Books" height="100" width="100"></img>Why Is Reading Important?
				<img src="http://pngimg.com/uploads/book/book_PNG2105.png" alt="Books" height="100" width="100"></img></h2>
			<p>Reading is fundamental to functioning in today's society.Reading is important because it develops the mind. The mind is a muscle. It needs exercise.  Reading develops the imagination. TV and computer games have their place, but they are more like amusement.  Amusement is non-thinking activities. A person who knows how to read can educate themselves in any area of life they are interested in. We live in an age where we overflow with information, but reading is the main way to take advantage of it. </p>
			<p> Finally, why is reading important?  Reading is important because words - spoken and written - are the building blocks of life. You are, right now, the result of words that you have heard or read AND believed about yourself. What you become in the future will depend on the words you believe about yourself now. People, families, relationships, and even nations are built from words. Think about it.</p>
		</div>	
	</div>
	<div class="container ">
		<div class="row">
		<div class="col-lg-4 ">
			<h2 class=" font-italic" >First Novel In The History!!</h2>
			<p>
				In the 11th century, a Japanese woman known as Murasaki Shikibu wrote “The Tale of Genji,” a 54-chapter story of courtly seduction believed to be the world’s first novel.<br>
Nearly 2,000 years later, people the world over are still engrossed by novels — even in an era where stories appear on handheld screens and disappear 24 hours later.<br>
What exactly do human beings get from reading books? <br> it just a matter of pleasure, or are there benefits beyond enjoyment? <br> Scientific answer is a resounding “yes.”

Reading books benefits both your physical and mental health, and those benefits can last a lifetime. They begin in early childhood and continue through the senior years. 
			</p>
			<p>
				For More Bookish content find us on:-
				<ul class="nav flex-column">
					<li class="nav-item">
						<a class="nav-link"href="#"><span class="fab fa-twitter-square">Twitter</span></a>
					</li>
					<li class="nav-item">
						<a class="nav-link"href="#"><span class="fab fa-instagram">Instagram</span></a>
					</li>
					<li class="nav-item">
						<a class="nav-link"href="#"><span class="fa fa-square">Book Blog</span></a>
					</li>
					<li class="nav-item">
						<a class="nav-link"href="#"><span class="fa fa-book">Goodreads</span></a>
					</li>
				</ul>
			</p>
		</div>
		<div class ="col-lg-4   text-body">
            <img src="{% static 'my_contact_data/books.png' %}" alt="Books" style="width:100%;height: 200px">

			<h2>Find Your Favourite Genre Today!</h2>
			<ul>
				<li>Historic Fiction</li>
				<li>Science Fiction</li>
				<li>Fantasy</li>
				<li>Contemporary</li>
				<li>Classics</li>
				<li>Literary Fiction</li>
				<li>Mystery/Thrillers</li>
				<li>Memoirs/Autobiographies</li>
				<li>Non-Fiction</li>
			</ul>
            
		</div>		
		<div class="col-lg-4 ">
			<h2>What Should You Be Reading?</h2>
			<img src="https://pngimg.com/uploads/book/book_PNG2120.png" alt="Logo" height="200" width="300">
			<p>
                So, what should you be reading? The short answer is:<br> Whatever you can get your hands on.
There was a time when remote regions had to rely on librarians traversing the mountains with books stuffed in saddlebags. But that’s hardly the case today. Just about everyone can access vast libraries contained in cellphones and tablets.

            </p>
	</div>
	<div class="container">
		<div class="copy">
			<center>
				<h6>&copy;2020 BooksforLife</h6>
			</center>

		</div>
	</div>


{% endblock %}
 
{% block script %}
{% endblock %}